kubernetesClusterDomain: cluster.local
env:
  serverPort: "8080"
image:
  repository: nexus-repo:30022/arpal-audit-ms-k8s-image
  tag: "1.0"
imagePullPolicy: Always
resources:
  limits:
    cpu: ""
    memory: 500i
  requests:
    cpu: "0.5"
    memory: 256Mi
ports:
- name: http
  port: 8080
  protocol: TCP
  targetPort: 8080
replicas: 1
type: ClusterIP